### ISSUE TITLE
need for etchash pool

### ISSUE THREAD

**Issue by galiy** [yuriy0803/etchash#3]
Compile error in etchash pool
proxy/miner.go:77:39: cannot use share (variable of type Block) as etchash.Block value in argument to hasher.Verify: Block does not implement etchash.Block (wrong type for method HashNoNonce)
		have HashNoNonce() "github.com/etclabscore/core-geth/common".Hash
		want HashNoNonce() "github.com/ethereum/go-ethereum/common".Hash
proxy/miner.go:88:30: cannot use block (variable of type Block) as etchash.Block value in argument to hasher.Verify: Block does not implement etchash.Block (wrong type for method HashNoNonce)
		have HashNoNonce() "github.com/etclabscore/core-geth/common".Hash
		want HashNoNonce() "github.com/ethereum/go-ethereum/common".Hash

![image](https://user-images.githubusercontent.com/23344960/223503885-0c08dea8-0622-484d-b6ce-6e6718d69211.png)

**Comment by yuriy0803** [comment]
hello everything works fine


https://github.com/yuriy0803/open-etc-pool-friends

**Comment by galiy** [comment]
Sorry, the problem is not in your pool, but, I think, in your library :-) incompatibility :-) Of course, I'm not a big specialist yet, but I think so. https://github.com/topdefi/open-evm-pool

**Comment by yuriy0803** [comment]
it's just old version
  https://github.com/topdefi/open-evm-pool
